# .streamlit/secrets.toml


db_username = "Bhanu"
db_password = "Tharakram123"

[data]
file_path = "C:/Users/Bhanu prakash/OneDrive - Vijaybhoomi International School/Desktop/Pycaret_SS/MRTSSM4451USS_edited.xlsx"